In [90]:
%load_ext autoreload
%autoreload 2

from model import *



from torch import empty, cat, arange
from torch.nn.functional import fold, unfold
from torch import nn

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [117]:
x = torch.randn((1, 3, 4, 4))

# x = torch.tensor(
    # [[0, 1., 0],     
    # [2, 0, 0],
    # [0, 0, 1]])

# y = torch.ones(x.shape)
y = torch.ones((1, 3, 4, 4))

x, y

(tensor([[[[-0.4824, -0.6209, -0.5491,  1.4126],
           [ 0.9026,  0.4973,  0.7036,  0.1052],
           [ 0.1208,  0.4672,  0.3177, -0.3503],
           [ 0.4333,  0.1192, -0.0154,  0.0895]],
 
          [[-0.3998,  0.3990,  0.2004, -1.2182],
           [-0.0228, -0.1671,  0.0234,  0.5751],
           [-2.2822,  0.6183,  0.8200,  0.3908],
           [-1.6932,  0.4957,  0.6846,  0.8520]],
 
          [[-1.9833, -0.3406,  0.1303, -0.3738],
           [ 0.3630, -0.9165,  1.2380,  1.1943],
           [-0.4236, -1.2962, -0.2713, -0.5865],
           [-0.6790,  0.3142,  1.0412,  0.5597]]]]),
 tensor([[[[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]],
 
          [[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]]]]))

In [107]:
conv = nn.Conv2d(3, 4, 2)
expected = conv(x)

In [108]:
# torch.nn.Unfold(kernel_size=2)(x)

kernel_size = (2, 2)
out_channels = 4

# Output of convolution as a matrix product
unfolded = torch.nn.functional.unfold(x, kernel_size=kernel_size)
# unfolded

wxb = conv.weight.view(out_channels, -1) @ unfolded + conv.bias.view(1, -1, 1)
actual = wxb.view(1, out_channels, x.shape[2] - kernel_size[0] + 1, x.shape[3] - kernel_size[1]+ 1)
torch.testing.assert_allclose(actual, expected)

In [122]:
conv.weight.view(out_channels, -1).size()

torch.Size([4, 12])

In [118]:
x.size()

torch.Size([1, 3, 4, 4])

In [112]:
unfolded.size()

torch.Size([1, 12, 9])

In [115]:

wxb.size()

torch.Size([1, 4, 9])

In [81]:
# relu = ReLU()
f=Sigmoid()

f.forward(x)

tensor([[0.5000, 0.7311, 0.5000],
        [0.8808, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.7311]])

In [82]:
f.backward(y)

tensor([[0.5000, 0.2689, 0.5000],
        [0.1192, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.2689]])